--- 
apiVersion: "1"
version: "1"
kind: "pipeline"
metadata:
  name: "maven-ci-pipeline"
  description: "CI Pipeline for Maven Project"
agent:
  label: "maven"
stages:
  - stage: "Checkout"
    steps:
      - checkout: "scm"
  - stage: "Build"
    steps:
      - sh: "mvn clean install"
  - stage: "Test"
    steps:
      - sh: "mvn test"
  - stage: "SonarQube Analysis"
    steps:
      - withSonarQubeEnv: "SonarQube"
        sh: "mvn sonar:sonar"
  - stage: "Publish Test Results"
    steps:
      - junit: "**/target/surefire-reports/*.xml"
