-- Query 3: Calculate total revenue per doctor
-- This query calculates the total revenue generated by each doctor from all their appointments

SELECT 
    d.doctor_id,
    d.name AS doctor_name,
    d.specialty,
    COUNT(a.appointment_id) AS total_appointments,
    SUM(b.amount) AS total_revenue,
    AVG(b.amount) AS average_bill_amount
FROM doctors d
INNER JOIN appointments a ON d.doctor_id = a.doctor_id
INNER JOIN bills b ON a.appointment_id = b.appointment_id
GROUP BY d.doctor_id, d.name, d.specialty
ORDER BY total_revenue DESC;